# Generated by Django 4.2.3 on 2023-07-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_alter_snack_description_alter_snack_purchaser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='title',
            new_name='name',
        ),
    ]
